import { IsNotEmpty, IsString } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class TwoFactorAuthCodeDto {
  @ApiProperty({
    description: 'Code generated by Authenticator',
    example: '101456',
  })
  @IsString()
  @IsNotEmpty()
  twoFactorCode: string;
}
